version: "3.8"

services:
  app:
    build:
      context: .
      args:
        PORT: ${PORT:-3000}
    container_name: nestjs-app
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file: .env
    environment:
      - PORT=${PORT:-3000}
